# Generated by Django 4.1 on 2022-08-31 19:26

import apps.video.check_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos', validators=[apps.video.check_size.file_size]),
        ),
    ]
